services:
  backend:
    build: ./backend
    container_name: prodigyai_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./backend:/app

  db:
    image: postgres:16
    container_name: prodigyai_postgres
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: prodigyai_redis
    ports:
      - "6380:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: prodigyai_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
